### PR TITLE
Add Discordant Stars factions

### PR DESCRIPTION
**Pull request by JoelNarr**
Adding Discordant Stars factions to the backend. Initially only selectable through the custom factions selection, but gets the framework in place for adding checkboxes in the future.

### CODE REVIEW

**Comment by JoelNarr** [comment]
Added in checkboxes to select the factions you want included in the draft, reworking a couple sections to give more options. I believe this is done, but I haven't been able to test fully.

**Comment by shenanigans-be** [comment]
@JoelNarr Awesome. Great work! I was really dreading looking up all the new faction icons so thanks a lot for doing that for me! 😅

I'm going to tweak some stuff and integrate this into the big update I'm working on!

**Comment by shenanigans-be** [comment]
@JoelNarr The update is live ([more info on reddit](https://www.reddit.com/r/twilightimperium/comments/144zs1a/milty_draft_generator_now_supports_discordant/))! Thanks for all the great work. If you'd like to be credited in some specific way just let me know!

**Comment by JoelNarr** [comment]
Awesome! Glad to see it come to fruition! No credit necessary for me, I'm just glad I was able to help out. Thanks for putting this together!

**Pull request merged**
